name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build services with Docker Compose
        run: |
          docker compose -f docker-compose.prod.yml build

      - name: Push services with Docker Compose
        run: |
          docker compose -f docker-compose.prod.yml push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH and redeploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            cd /path/to/project

            docker compose -f docker-compose.prod.yml pull

            docker compose -f docker-compose.prod.yml up -d

            docker image prune -f
